### ISSUE TITLE
add searchbar to docs

### ISSUE THREAD

**Issue by lyyva** [bisq-network/bisq-docs#128]
this could be very helpful for anyone quickly wanting to look up something specific

**Comment by m52go** [comment]
@lyyva agree, but the framework we currently use for documentation (AsciiDoctor) doesn't make this easy. Almost anything that isn't offered by default is a big pain to integrate.

AsciiDoc poses other significant limitations as well. Most notably, interface options are very limited, which you can see in a front page that is extremely dense with text. This will get progressively worse as the number of docs grows over time.

It makes more sense to me to migrate the whole docs repository away from AsciiDoc to another framework altogether, instead of wrestling with AsciiDoctor for features that are already integrated in other frameworks. When we do this, search will certainly be a required feature.

**Comment by m52go** [comment]
I've created #131 to address this item.

**Comment by HarryMacfinned** [comment]
It's possible to do searches here directly in the github.
Not very convenient I agree, but still a possible hack.
