### ISSUE TITLE
Add links to old documentation

### ISSUE THREAD

**Issue by HarryMacfinned** [bisq-network/bisq-docs#68]
A little question/suggestion:
The whitepaper is now (relegated) in the archive part of the docs: https://docs.bisq.network/
The whitepaper itself references several other documents:
risk-analysis.pdf, p2p-network.pdf, arbitration-system.pdf, and maybe others.

The links and formats are heterogeneous : google docs, webarchive, ...

I didn't find those (interesting imho) docs neither on github neither on https://docs.bisq.network/ (apologies if I searched badly).
Would it be interesting to rapatriate those docs on those 2 places ? (or it's considered too obsolete ?)

**Comment by cbeams** [comment]
It would be fine to, at a minumum, add links to all existing docs in their current locations to the Archive section of docs.bisq.network. I don't want to put any of them front and center, though, as they are all quite old, have varying quality of writing style and formatting, etc. Generally, we want updated versions of these docs everywhere, and not just transcribed / touched-up versions. So adding links to the archive is great, but let's not bother with transcribing them into asciidoc, etc. Please double-check also that the docs in question haven't already been transcribed in the `exchange` folder under the bisq-network/bisq-docs repository. Pull requests welcome.

As an aside, please also study how titles of issues are usually created here in bisq-network GitHub repositories. Rather than:

> old documentation ?

it would be better to title the issue something like:

> Add links to old documentation

Generally, form issues as imperative statements rather than questions. Use conventional sentence capitalization, avoid punctuation at statement end.

If you do create a pull request to add these links to the archive, please reference this issue in the pull request description by mentioning #68. You can use the keyword "Fixes", e.g. "Fixes #68" in the description of the pull request, and that will cause this issue to be closed automatically if and when the pull request is merged. See https://help.github.com/articles/closing-issues-using-keywords/ for details.

**Comment by HarryMacfinned** [comment]
> Please double-check also that the docs in question haven't already been transcribed in the exchange folder under the bisq-network/bisq-docs repository. 

No. I did verify before asking and I didn't find them at this place.

Thanks for all the other advices ... (I'll have understood github when Bisq will leave from there !)

**Comment by cbeams** [comment]
Closing as answered.
